#include <ncurses.h>
#include "windowManager.h"
#include "gameManager.h"
#include "player.h"
#include "defendWindow.h"
#include "attackWindow.h"
#include "statusWindow.h"
#include "inputWindow.h"
#include "ship.h"